# Build stage
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci

ARG SUPABASE_URL
ARG SUPABASE_ANON_KEY
ARG SUPABASE_STORAGE_URL
ARG SUPABASE_BUCKET_NAME
ARG JS_REPORT_URL
ARG JS_REPORT_TOKEN
ARG N8N_WEBHOOK_URL
ARG EVO_API_URL
ARG EVO_API_KEY
ARG EVO_INSTANCE_NAME

ENV SUPABASE_URL=$SUPABASE_URL \
    SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY \
    SUPABASE_STORAGE_URL=$SUPABASE_STORAGE_URL \
    SUPABASE_BUCKET_NAME=$SUPABASE_BUCKET_NAME \
    JS_REPORT_URL=$JS_REPORT_URL \
    JS_REPORT_TOKEN=$JS_REPORT_TOKEN \
    N8N_WEBHOOK_URL=$N8N_WEBHOOK_URL \
    EVO_API_URL=$EVO_API_URL \
    EVO_API_KEY=$EVO_API_KEY \
    EVO_INSTANCE_NAME=$EVO_INSTANCE_NAME

COPY . .
RUN npm run build

# Production stage
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]