-- ══════════════════════════════════════════════════════════════════════════════
-- SISCAD AAFC — Script de auditoria: tabela audit_logs + triggers genéricos
-- Execute no SQL Editor do Supabase na ordem em que está escrito
-- ══════════════════════════════════════════════════════════════════════════════


-- ─────────────────────────────────────────────────────────────────────────────
-- 1. TABELA: audit_logs (Registro de auditoria)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_date  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'::TEXT),
  user_uuid     UUID NULL,
  table_name    TEXT NULL,
  operation     TEXT NULL,
  data_old      JSONB NULL,
  data_new      JSONB NULL,
  user_id       BIGINT NULL,
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_audit_logs_created_date   ON public.audit_logs (created_date DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_table_name     ON public.audit_logs (table_name);
CREATE INDEX IF NOT EXISTS idx_audit_logs_operation      ON public.audit_logs (operation);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_uuid      ON public.audit_logs (user_uuid);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id        ON public.audit_logs (user_id);

COMMENT ON TABLE  public.audit_logs            IS 'Auditoria de operações INSERT/UPDATE/DELETE nas tabelas do sistema';
COMMENT ON COLUMN public.audit_logs.created_date IS 'Data/hora da operação (UTC)';
COMMENT ON COLUMN public.audit_logs.user_uuid   IS 'UUID do usuário Supabase Auth que realizou a operação';
COMMENT ON COLUMN public.audit_logs.table_name  IS 'Nome da tabela afetada';
COMMENT ON COLUMN public.audit_logs.operation   IS 'Tipo da operação: INSERT, UPDATE ou DELETE';
COMMENT ON COLUMN public.audit_logs.data_old    IS 'Dados anteriores à operação (JSONB) — nulo para INSERT';
COMMENT ON COLUMN public.audit_logs.data_new    IS 'Dados posteriores à operação (JSONB) — nulo para DELETE';
COMMENT ON COLUMN public.audit_logs.user_id     IS 'ID numérico do usuário na tabela users';


-- ─────────────────────────────────────────────────────────────────────────────
-- 2. FUNÇÃO: fn_audit() — trigger genérico de auditoria
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.fn_audit()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user_uuid UUID;
  v_user_id   BIGINT;
BEGIN
  -- Extrair UUID do usuário a partir do JWT (Supabase Auth)
  BEGIN
    v_user_uuid := (CURRENT_SETTING('request.jwt.claims')::JSON)->>'sub';
  EXCEPTION WHEN OTHERS THEN
    v_user_uuid := NULL;
  END;

  -- Buscar o ID numérico do usuário na tabela users
  IF v_user_uuid IS NOT NULL THEN
    SELECT id INTO v_user_id
    FROM public.users
    WHERE uuid = v_user_uuid::TEXT
    LIMIT 1;
  END IF;

  IF TG_OP = 'INSERT' THEN
    INSERT INTO public.audit_logs (user_uuid, table_name, operation, data_old, data_new, user_id)
    VALUES (v_user_uuid, TG_TABLE_NAME, 'INSERT', NULL, TO_JSONB(NEW), v_user_id);
    RETURN NEW;

  ELSIF TG_OP = 'UPDATE' THEN
    -- So insere log se os dados realmente mudaram
    IF TO_JSONB(OLD) IS DISTINCT FROM TO_JSONB(NEW) THEN
      INSERT INTO public.audit_logs (user_uuid, table_name, operation, data_old, data_new, user_id)
      VALUES (v_user_uuid, TG_TABLE_NAME, 'UPDATE', TO_JSONB(OLD), TO_JSONB(NEW), v_user_id);
    END IF;
    RETURN NEW;

  ELSIF TG_OP = 'DELETE' THEN
    INSERT INTO public.audit_logs (user_uuid, table_name, operation, data_old, data_new, user_id)
    VALUES (v_user_uuid, TG_TABLE_NAME, 'DELETE', TO_JSONB(OLD), NULL, v_user_id);
    RETURN OLD;
  END IF;

  RETURN NULL;
END;
$$;


-- ─────────────────────────────────────────────────────────────────────────────
-- 3. TRIGGERS: auditoria em cada tabela
-- ─────────────────────────────────────────────────────────────────────────────

-- members
DROP TRIGGER IF EXISTS audit_members ON public.members;
CREATE TRIGGER audit_members
  AFTER INSERT OR UPDATE OR DELETE ON public.members
  FOR EACH ROW EXECUTE FUNCTION public.fn_audit();

-- meetings
DROP TRIGGER IF EXISTS audit_meetings ON public.meetings;
CREATE TRIGGER audit_meetings
  AFTER INSERT OR UPDATE OR DELETE ON public.meetings
  FOR EACH ROW EXECUTE FUNCTION public.fn_audit();

-- meetings_members
DROP TRIGGER IF EXISTS audit_meetings_members ON public.meetings_members;
CREATE TRIGGER audit_meetings_members
  AFTER INSERT OR UPDATE OR DELETE ON public.meetings_members
  FOR EACH ROW EXECUTE FUNCTION public.fn_audit();

-- users
DROP TRIGGER IF EXISTS audit_users ON public.users;
CREATE TRIGGER audit_users
  AFTER INSERT OR UPDATE OR DELETE ON public.users
  FOR EACH ROW EXECUTE FUNCTION public.fn_audit();

-- profiles
DROP TRIGGER IF EXISTS audit_profiles ON public.profiles;
CREATE TRIGGER audit_profiles
  AFTER INSERT OR UPDATE OR DELETE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.fn_audit();

-- permissions
DROP TRIGGER IF EXISTS audit_permissions ON public.permissions;
CREATE TRIGGER audit_permissions
  AFTER INSERT OR UPDATE OR DELETE ON public.permissions
  FOR EACH ROW EXECUTE FUNCTION public.fn_audit();

-- plans
DROP TRIGGER IF EXISTS audit_plans ON public.plans;
CREATE TRIGGER audit_plans
  AFTER INSERT OR UPDATE OR DELETE ON public.plans
  FOR EACH ROW EXECUTE FUNCTION public.fn_audit();

-- regions
DROP TRIGGER IF EXISTS audit_regions ON public.regions;
CREATE TRIGGER audit_regions
  AFTER INSERT OR UPDATE OR DELETE ON public.regions
  FOR EACH ROW EXECUTE FUNCTION public.fn_audit();

-- genders
DROP TRIGGER IF EXISTS audit_genders ON public.genders;
CREATE TRIGGER audit_genders
  AFTER INSERT OR UPDATE OR DELETE ON public.genders
  FOR EACH ROW EXECUTE FUNCTION public.fn_audit();


-- ─────────────────────────────────────────────────────────────────────────────
-- 4. ROW LEVEL SECURITY (RLS)
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Leitura: apenas super-admins
DROP POLICY IF EXISTS "audit_logs: leitura apenas super admin" ON public.audit_logs;
CREATE POLICY "audit_logs: leitura apenas super admin"
  ON public.audit_logs FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.users u
      WHERE u.uuid = (CURRENT_SETTING('request.jwt.claims')::JSON)->>'sub'::TEXT
        AND u.is_admin_super = TRUE
    )
  );

-- Bloquear inserts/updates/deletes diretos via API (apenas triggers devem escrever)
DROP POLICY IF EXISTS "audit_logs: sem escrita direta" ON public.audit_logs;
CREATE POLICY "audit_logs: sem escrita direta"
  ON public.audit_logs FOR ALL
  TO authenticated
  USING (FALSE)
  WITH CHECK (FALSE);


-- ─────────────────────────────────────────────────────────────────────────────
-- 5. VIEW: v_audit_logs (facilita consultas com dados do usuário)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE VIEW public.v_audit_logs AS
SELECT
  l.id,
  l.created_date,
  l.user_uuid,
  u.name_full   AS user_name,
  u.email        AS user_email,
  l.table_name,
  l.operation,
  l.data_old,
  l.data_new,
  l.user_id
FROM public.audit_logs l
LEFT JOIN public.users u ON u.uuid = l.user_uuid::TEXT
ORDER BY l.created_date DESC;

COMMENT ON VIEW public.v_audit_logs IS 'View de auditoria com dados do usuário';


-- ══════════════════════════════════════════════════════════════════════════════
-- FIM DO SCRIPT
-- ══════════════════════════════════════════════════════════════════════════════
